// Code generated by genforward. DO NOT EDIT.

package forwardgen

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/pj-hoakari/tolo-observation/gen/tolo/observation/v1"
	observationv1connect "github.com/pj-hoakari/tolo-observation/gen/tolo/observation/v1/observationv1connect"
	forward "github.com/pj-hoakari/tolo-service-gateway/internal/infra/connect/forward"
)

type toloObservationV1MeasurementIngestServiceForwarder struct {
	client observationv1connect.MeasurementIngestServiceClient
}

func (f *toloObservationV1MeasurementIngestServiceForwarder) ReportMeasurements(ctx context.Context, req *connect.Request[v1.ReportMeasurementsRequest]) (*connect.Response[v1.ReportMeasurementsResponse], error) {
	return forward.Unary(ctx, req, f.client.ReportMeasurements)
}

type toloObservationV1EdgeDeviceServiceForwarder struct {
	client observationv1connect.EdgeDeviceServiceClient
}

func (f *toloObservationV1EdgeDeviceServiceForwarder) RegisterEdgeDevice(ctx context.Context, req *connect.Request[v1.RegisterEdgeDeviceRequest]) (*connect.Response[v1.RegisterEdgeDeviceResponse], error) {
	return forward.Unary(ctx, req, f.client.RegisterEdgeDevice)
}

func (f *toloObservationV1EdgeDeviceServiceForwarder) UnregisterEdgeDevice(ctx context.Context, req *connect.Request[v1.UnregisterEdgeDeviceRequest]) (*connect.Response[v1.UnregisterEdgeDeviceResponse], error) {
	return forward.Unary(ctx, req, f.client.UnregisterEdgeDevice)
}

func (f *toloObservationV1EdgeDeviceServiceForwarder) ListEdgeDevices(ctx context.Context, req *connect.Request[v1.ListEdgeDevicesRequest]) (*connect.Response[v1.ListEdgeDevicesResponse], error) {
	return forward.Unary(ctx, req, f.client.ListEdgeDevices)
}

func (f *toloObservationV1EdgeDeviceServiceForwarder) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return forward.Unary(ctx, req, f.client.Heartbeat)
}

func (f *toloObservationV1EdgeDeviceServiceForwarder) UpdateObservationPointConfig(ctx context.Context, req *connect.Request[v1.UpdateObservationPointConfigRequest]) (*connect.Response[v1.UpdateObservationPointConfigResponse], error) {
	return forward.Unary(ctx, req, f.client.UpdateObservationPointConfig)
}
