// Code generated by genforward. DO NOT EDIT.

package forwardgen

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "github.com/pj-hoakari/tolo-graph-authoring/gen/tolo/graph/v1"
	graphv1connect "github.com/pj-hoakari/tolo-graph-authoring/gen/tolo/graph/v1/graphv1connect"
	v11 "github.com/pj-hoakari/tolo-graph-authoring/gen/tolo/kernel/v1"
	forward "github.com/pj-hoakari/tolo-service-gateway/internal/infra/connect/forward"
)

type toloGraphV1GraphAuthoringServiceForwarder struct {
	client graphv1connect.GraphAuthoringServiceClient
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) SaveGraph(ctx context.Context, req *connect.Request[v1.SaveGraphRequest]) (*connect.Response[v1.GraphMeta], error) {
	return forward.Unary(ctx, req, f.client.SaveGraph)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) MapObservationPoint(ctx context.Context, req *connect.Request[v1.MapObservationPointRequest]) (*connect.Response[v1.ObservationPointMapping], error) {
	return forward.Unary(ctx, req, f.client.MapObservationPoint)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) AddQrLocation(ctx context.Context, req *connect.Request[v1.AddQrLocationRequest]) (*connect.Response[v1.QrLocation], error) {
	return forward.Unary(ctx, req, f.client.AddQrLocation)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) UpdateQrLocation(ctx context.Context, req *connect.Request[v1.UpdateQrLocationRequest]) (*connect.Response[v1.QrLocation], error) {
	return forward.Unary(ctx, req, f.client.UpdateQrLocation)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) RemoveQrLocation(ctx context.Context, req *connect.Request[v1.RemoveQrLocationRequest]) (*connect.Response[v1.RemoveResponse], error) {
	return forward.Unary(ctx, req, f.client.RemoveQrLocation)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) GetGraph(ctx context.Context, req *connect.Request[v1.GetGraphRequest]) (*connect.Response[v1.GetGraphResponse], error) {
	return forward.Unary(ctx, req, f.client.GetGraph)
}

func (f *toloGraphV1GraphAuthoringServiceForwarder) PublishRevision(ctx context.Context, req *connect.Request[v1.PublishRevisionRequest]) (*connect.Response[v1.GraphMeta], error) {
	return forward.Unary(ctx, req, f.client.PublishRevision)
}

type toloGraphV1GraphSupplyServiceForwarder struct {
	client graphv1connect.GraphSupplyServiceClient
}

func (f *toloGraphV1GraphSupplyServiceForwarder) GetCurrentRevision(ctx context.Context, req *connect.Request[v1.GetCurrentRevisionRequest]) (*connect.Response[v11.Graph], error) {
	return forward.Unary(ctx, req, f.client.GetCurrentRevision)
}

func (f *toloGraphV1GraphSupplyServiceForwarder) GetObservationPointMappings(ctx context.Context, req *connect.Request[v1.GetMappingsRequest]) (*connect.Response[v1.GetMappingsResponse], error) {
	return forward.Unary(ctx, req, f.client.GetObservationPointMappings)
}

func (f *toloGraphV1GraphSupplyServiceForwarder) GetDisplayNames(ctx context.Context, req *connect.Request[v1.GetDisplayNamesRequest]) (*connect.Response[v1.GetDisplayNamesResponse], error) {
	return forward.Unary(ctx, req, f.client.GetDisplayNames)
}

func (f *toloGraphV1GraphSupplyServiceForwarder) GetGatePoints(ctx context.Context, req *connect.Request[v1.GetGatePointsRequest]) (*connect.Response[v1.GetGatePointsResponse], error) {
	return forward.Unary(ctx, req, f.client.GetGatePoints)
}

func (f *toloGraphV1GraphSupplyServiceForwarder) GetQrLocations(ctx context.Context, req *connect.Request[v1.GetQrLocationsRequest]) (*connect.Response[v1.GetQrLocationsResponse], error) {
	return forward.Unary(ctx, req, f.client.GetQrLocations)
}
