// Code generated by genforward. DO NOT EDIT.

package forwardgen

import (
	connect "connectrpc.com/connect"
	context "context"
	forward "github.com/pj-hoakari/tolo-service-gateway/internal/infra/connect/forward"
	v1 "github.com/pj-hoakari/tolo-tenant-management/gen/tolo/tenant/v1"
	tenantv1connect "github.com/pj-hoakari/tolo-tenant-management/gen/tolo/tenant/v1/tenantv1connect"
)

type toloTenantV1TenantServiceForwarder struct {
	client tenantv1connect.TenantServiceClient
}

func (f *toloTenantV1TenantServiceForwarder) StartTenantRegistration(ctx context.Context, req *connect.Request[v1.StartTenantRegistrationRequest]) (*connect.Response[v1.StartTenantRegistrationResponse], error) {
	return forward.Unary(ctx, req, f.client.StartTenantRegistration)
}

func (f *toloTenantV1TenantServiceForwarder) ClaimTenantOwnership(ctx context.Context, req *connect.Request[v1.ClaimTenantOwnershipRequest]) (*connect.Response[v1.ClaimTenantOwnershipResponse], error) {
	return forward.Unary(ctx, req, f.client.ClaimTenantOwnership)
}

func (f *toloTenantV1TenantServiceForwarder) ChangeTenantContract(ctx context.Context, req *connect.Request[v1.ChangeTenantContractRequest]) (*connect.Response[v1.ChangeTenantContractResponse], error) {
	return forward.Unary(ctx, req, f.client.ChangeTenantContract)
}

func (f *toloTenantV1TenantServiceForwarder) ArchiveTenant(ctx context.Context, req *connect.Request[v1.ArchiveTenantRequest]) (*connect.Response[v1.ArchiveTenantResponse], error) {
	return forward.Unary(ctx, req, f.client.ArchiveTenant)
}

func (f *toloTenantV1TenantServiceForwarder) CreateEvent(ctx context.Context, req *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error) {
	return forward.Unary(ctx, req, f.client.CreateEvent)
}

func (f *toloTenantV1TenantServiceForwarder) AssignEventType(ctx context.Context, req *connect.Request[v1.AssignEventTypeRequest]) (*connect.Response[v1.AssignEventTypeResponse], error) {
	return forward.Unary(ctx, req, f.client.AssignEventType)
}

func (f *toloTenantV1TenantServiceForwarder) TransitionEventStatus(ctx context.Context, req *connect.Request[v1.TransitionEventStatusRequest]) (*connect.Response[v1.TransitionEventStatusResponse], error) {
	return forward.Unary(ctx, req, f.client.TransitionEventStatus)
}

func (f *toloTenantV1TenantServiceForwarder) GetEvent(ctx context.Context, req *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return forward.Unary(ctx, req, f.client.GetEvent)
}

func (f *toloTenantV1TenantServiceForwarder) GetObservationSettings(ctx context.Context, req *connect.Request[v1.GetObservationSettingsRequest]) (*connect.Response[v1.GetObservationSettingsResponse], error) {
	return forward.Unary(ctx, req, f.client.GetObservationSettings)
}

func (f *toloTenantV1TenantServiceForwarder) UpdateObservationSettings(ctx context.Context, req *connect.Request[v1.UpdateObservationSettingsRequest]) (*connect.Response[v1.UpdateObservationSettingsResponse], error) {
	return forward.Unary(ctx, req, f.client.UpdateObservationSettings)
}

func (f *toloTenantV1TenantServiceForwarder) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return forward.Unary(ctx, req, f.client.ListEvents)
}
