package main

import (
	"errors"
	"strings"
	"testing"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const testProtoPath = "example/v1/example.proto"

func testFileDescriptor() *descriptorpb.FileDescriptorProto {
	message := func(name string) *descriptorpb.DescriptorProto {
		return &descriptorpb.DescriptorProto{Name: proto.String(name)}
	}

	method := func(name string, streamed bool) *descriptorpb.MethodDescriptorProto {
		return &descriptorpb.MethodDescriptorProto{
			Name:            proto.String(name),
			InputType:       proto.String(".example.v1.Request"),
			OutputType:      proto.String(".example.v1.Response"),
			ServerStreaming: proto.Bool(streamed),
		}
	}

	return &descriptorpb.FileDescriptorProto{
		Name:    proto.String(testProtoPath),
		Package: proto.String("example.v1"),
		Syntax:  proto.String("proto3"),
		Options: &descriptorpb.FileOptions{
			GoPackage: proto.String("example.com/gen/example/v1;examplev1"),
		},
		MessageType: []*descriptorpb.DescriptorProto{message("Request"), message("Response")},
		Service: []*descriptorpb.ServiceDescriptorProto{
			{
				Name:   proto.String("BoundService"),
				Method: []*descriptorpb.MethodDescriptorProto{method("Do", false), method("Undo", false)},
			},
			{
				Name:   proto.String("StreamingService"),
				Method: []*descriptorpb.MethodDescriptorProto{method("Watch", true)},
			},
			{
				Name:   proto.String("UnboundService"),
				Method: []*descriptorpb.MethodDescriptorProto{method("Hidden", false)},
			},
		},
	}
}

func newTestPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	var options protogen.Options

	plugin, err := options.New(&pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{testProtoPath},
		ProtoFile:      []*descriptorpb.FileDescriptorProto{testFileDescriptor()},
	})
	if err != nil {
		t.Fatalf("protogen.Options.New() error = %v, want nil", err)
	}

	return plugin
}

func generated(t *testing.T, plugin *protogen.Plugin) map[string]string {
	t.Helper()

	response := plugin.Response()
	if response.GetError() != "" {
		t.Fatalf("plugin response error = %q, want none", response.GetError())
	}

	files := make(map[string]string, len(response.GetFile()))
	for _, file := range response.GetFile() {
		files[file.GetName()] = file.GetContent()
	}

	return files
}

func TestGenerateWritesForwardersForBoundServicesOnly(t *testing.T) {
	t.Parallel()

	plugin := newTestPlugin(t)

	if err := Generate(plugin, map[string]struct{}{"example.v1.BoundService": {}}); err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}

	files := generated(t, plugin)

	forwarders, ok := files["example_v1_example.forward.go"]
	if !ok {
		t.Fatalf("generated files = %v, want one named example_v1_example.forward.go", files)
	}

	for _, want := range []string{
		"// Code generated by genforward. DO NOT EDIT.",
		"package forwardgen",
		"type exampleV1BoundServiceForwarder struct {",
		"func (f *exampleV1BoundServiceForwarder) Do(",
		"func (f *exampleV1BoundServiceForwarder) Undo(",
		"return forward.Unary(ctx, req, f.client.Do)",
	} {
		if !strings.Contains(forwarders, want) {
			t.Errorf("the generated forwarders do not contain %q\ngot:\n%s", want, forwarders)
		}
	}

	for _, unwanted := range []string{"UnboundService", "StreamingService", "Unimplemented"} {
		if strings.Contains(forwarders, unwanted) {
			t.Errorf("the generated forwarders name %q, want them not to\ngot:\n%s", unwanted, forwarders)
		}
	}

	mounts, ok := files["mounts.forward.go"]
	if !ok {
		t.Fatalf("generated files = %v, want one named mounts.forward.go", files)
	}

	for _, want := range []string{
		"func Mounts() []forward.Mount {",
		"Service: examplev1connect.BoundServiceName,",
		"examplev1connect.NewBoundServiceHandler(",
		"examplev1connect.NewBoundServiceClient(httpClient, baseURL, clientOptions...)",
	} {
		if !strings.Contains(mounts, want) {
			t.Errorf("the generated mounts do not contain %q\ngot:\n%s", want, mounts)
		}
	}
}

func TestGenerateRejectsStreamingServices(t *testing.T) {
	t.Parallel()

	err := Generate(newTestPlugin(t), map[string]struct{}{"example.v1.StreamingService": {}})

	if !errors.Is(err, ErrStreamingMethod) {
		t.Errorf("Generate() error = %v, want %v", err, ErrStreamingMethod)
	}
}

func TestGenerateRejectsUnknownServices(t *testing.T) {
	t.Parallel()

	err := Generate(newTestPlugin(t), map[string]struct{}{"example.v1.AbsentService": {}})

	if !errors.Is(err, ErrUnknownService) {
		t.Errorf("Generate() error = %v, want %v", err, ErrUnknownService)
	}
}
