package main

import (
	"errors"
	"fmt"
	"maps"
	"path"
	"slices"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	forwardgenPackage    = protogen.GoPackageName("forwardgen")
	forwardgenImportPath = protogen.GoImportPath("github.com/pj-hoakari/tolo-service-gateway/internal/infra/connect/forwardgen")
	forwardImportPath    = protogen.GoImportPath("github.com/pj-hoakari/tolo-service-gateway/internal/infra/connect/forward")
	connectImportPath    = protogen.GoImportPath("connectrpc.com/connect")
	contextImportPath    = protogen.GoImportPath("context")
	httpImportPath       = protogen.GoImportPath("net/http")
)

const (
	generatedHeader = "// Code generated by genforward. DO NOT EDIT."
	fileSuffix      = ".forward.go"
	mountsFile      = "mounts" + fileSuffix
)

var (
	ErrStreamingMethod = errors.New("genforward: streaming method")
	ErrUnknownService  = errors.New("genforward: unknown service")
)

type forwarder struct {
	file    *protogen.File
	service *protogen.Service
}

func Generate(plugin *protogen.Plugin, services map[string]struct{}) error {
	var forwarders []forwarder

	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}

		bound := boundForwarders(file, services)
		if len(bound) == 0 {
			continue
		}

		if err := checkUnary(bound); err != nil {
			return err
		}

		generateForwarders(plugin, file, bound)

		forwarders = append(forwarders, bound...)
	}

	if err := checkComplete(forwarders, services); err != nil {
		return err
	}

	slices.SortFunc(forwarders, func(left, right forwarder) int {
		return strings.Compare(string(left.service.Desc.FullName()), string(right.service.Desc.FullName()))
	})

	generateMounts(plugin, forwarders)

	return nil
}

func boundForwarders(file *protogen.File, services map[string]struct{}) []forwarder {
	var bound []forwarder

	for _, service := range file.Services {
		if _, ok := services[string(service.Desc.FullName())]; ok {
			bound = append(bound, forwarder{file: file, service: service})
		}
	}

	return bound
}

func checkUnary(forwarders []forwarder) error {
	var errs []error

	for _, each := range forwarders {
		for _, method := range each.service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				errs = append(errs, fmt.Errorf("%w: %s cannot be forwarded", ErrStreamingMethod, method.Desc.FullName()))
			}
		}
	}

	return errors.Join(errs...)
}

func checkComplete(forwarders []forwarder, services map[string]struct{}) error {
	generated := make(map[string]struct{}, len(forwarders))

	for _, each := range forwarders {
		generated[string(each.service.Desc.FullName())] = struct{}{}
	}

	var errs []error

	for _, service := range slices.Sorted(maps.Keys(services)) {
		if _, ok := generated[service]; !ok {
			errs = append(errs, fmt.Errorf("%w: %s is not declared by any file to generate", ErrUnknownService, service))
		}
	}

	return errors.Join(errs...)
}

func generateForwarders(plugin *protogen.Plugin, file *protogen.File, forwarders []forwarder) {
	g := newGeneratedFile(plugin, fileNameOf(file))

	for _, each := range forwarders {
		connect := connectImportPathOf(each.file)
		name := forwarderNameOf(each.service)

		g.P("type ", name, " struct {")
		g.P("client ", g.QualifiedGoIdent(connect.Ident(each.service.GoName+"Client")))
		g.P("}")
		g.P()

		for _, method := range each.service.Methods {
			g.P("func (f *", name, ") ", method.GoName, "(",
				"ctx ", g.QualifiedGoIdent(contextImportPath.Ident("Context")), ", ",
				"req *", g.QualifiedGoIdent(connectImportPath.Ident("Request")), "[", g.QualifiedGoIdent(method.Input.GoIdent), "],",
				") (*", g.QualifiedGoIdent(connectImportPath.Ident("Response")), "[", g.QualifiedGoIdent(method.Output.GoIdent), "], error) {")
			g.P("return ", g.QualifiedGoIdent(forwardImportPath.Ident("Unary")), "(ctx, req, f.client.", method.GoName, ")")
			g.P("}")
			g.P()
		}
	}
}

func generateMounts(plugin *protogen.Plugin, forwarders []forwarder) {
	g := newGeneratedFile(plugin, mountsFile)
	mount := g.QualifiedGoIdent(forwardImportPath.Ident("Mount"))

	g.P("func Mounts() []", mount, " {")
	g.P("return []", mount, "{")

	for _, each := range forwarders {
		connect := connectImportPathOf(each.file)
		service := each.service

		g.P("{")
		g.P("Service: ", g.QualifiedGoIdent(connect.Ident(service.GoName+"Name")), ",")
		g.P("New: func(",
			"httpClient ", g.QualifiedGoIdent(connectImportPath.Ident("HTTPClient")), ", ",
			"baseURL string, ",
			"clientOptions []", g.QualifiedGoIdent(connectImportPath.Ident("ClientOption")), ", ",
			"handlerOptions []", g.QualifiedGoIdent(connectImportPath.Ident("HandlerOption")), ",",
			") (string, ", g.QualifiedGoIdent(httpImportPath.Ident("Handler")), ") {")
		g.P("return ", g.QualifiedGoIdent(connect.Ident("New"+service.GoName+"Handler")), "(")
		g.P("&", forwarderNameOf(service), "{client: ", g.QualifiedGoIdent(connect.Ident("New"+service.GoName+"Client")), "(httpClient, baseURL, clientOptions...)},")
		g.P("handlerOptions...,")
		g.P(")")
		g.P("},")
		g.P("},")
	}

	g.P("}")
	g.P("}")
}

func newGeneratedFile(plugin *protogen.Plugin, name string) *protogen.GeneratedFile {
	g := plugin.NewGeneratedFile(name, forwardgenImportPath)
	g.P(generatedHeader)
	g.P()
	g.P("package ", forwardgenPackage)
	g.P()

	return g
}

func fileNameOf(file *protogen.File) string {
	trimmed := strings.TrimSuffix(file.Desc.Path(), ".proto")

	return strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(trimmed) + fileSuffix
}

func connectImportPathOf(file *protogen.File) protogen.GoImportPath {
	return protogen.GoImportPath(path.Join(string(file.GoImportPath), string(file.GoPackageName)+"connect"))
}

func forwarderNameOf(service *protogen.Service) string {
	var words []string

	for _, part := range strings.Split(string(service.Desc.FullName()), ".") {
		for _, word := range strings.Split(part, "_") {
			if word == "" {
				continue
			}

			runes := []rune(word)
			if len(words) == 0 {
				runes[0] = unicode.ToLower(runes[0])
			} else {
				runes[0] = unicode.ToUpper(runes[0])
			}

			words = append(words, string(runes))
		}
	}

	return strings.Join(words, "") + "Forwarder"
}
